<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../dafny/Source/DafnyLanguageServer/DafnyLanguageServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Z3">
      <HintPath>lib\z3-4.14.1-x64-glibc-2.35\bin\Microsoft.Z3.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <None Update="lib/z3-4.14.1-x64-glibc-2.35/bin/libz3.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libz3.so</Link>
    </None>
  </ItemGroup>

</Project>
