using Microsoft.Dafny;
using Type = Microsoft.Dafny.Type;

namespace SnapshotGenerator.InvariantInference;

public class DaikonInstrumenter(List<Identifier> identifierAvailability) : Visitor(true)
{
    private TopLevelDeclWithMembers? _currentTopLevelDecl;
    private BlockStmt? _currentBlock;
    private readonly List<Method> _newMethods = [];
    private List<Statement> _newBlockBody = [];
    private readonly List<Statement> _newStmts = [];
    private readonly List<(ReturnStmt, BlockStmt)> _returnStmts = []; // (return stmt, enclosing block)
    
    public void Instrument(ModuleDefinition module) {
        Visit(module);
        if (SnapshotGenerator.MainMethod == null || 
            SnapshotGenerator.FaultyMethod == null)
            return;
        var mainMethod = SnapshotGenerator.MainMethod;
        var faultyMethod = SnapshotGenerator.FaultyMethod;
        AdjustTestExecution(mainMethod);
        
        AddHeader();
        AddMethodDeclaration(faultyMethod);
        AddDummyMethodsDeclarations();
        if (mainMethod.Body == null) {
            mainMethod.Body = new BlockStmt(mainMethod.Origin, _newStmts);
        } else {
            mainMethod.Body.Body = _newStmts.Concat(mainMethod.Body.Body).ToList();  
        }
        AddMethodTracePoints(faultyMethod);
        AddDummyMethodsTracePoints();
    }
    
    protected override void HandleMemberDecls(TopLevelDeclWithMembers decl) {
        _currentTopLevelDecl = decl;
        base.HandleMemberDecls(decl);
        decl.Members.AddRange(_newMethods);
    }
    
    protected override void HandleMethod(Method method) {
        // find Main, i.e., entrypoint, where the faulty method is being exercised
        if (method.Name == "Main")
            SnapshotGenerator.MainMethod = method;
        // find the faulty method, i.e., where the violation occurs  
        if (!(method.StartToken.line <= SnapshotGenerator.ViolationLine &&
              method.EndToken.line >= SnapshotGenerator.ViolationLine))
            return;
        SnapshotGenerator.FaultyMethod = method;
        
        // instrument the method with calls to dummy methods for invariant inference
        if (method.Body != null)
            HandleBlock(method.Body);
    }
    
    /// -------------------------
    /// Instrumentation
    /// -------------------------
    protected override void HandleBlock(BlockStmt blockStmt) {
        _currentBlock = blockStmt;
        var prevNewBlock = _newBlockBody;
        _newBlockBody = [];
        foreach (var (stmt, i) in blockStmt.Body.Select((stmt, i) => (stmt, i))) {
            _newBlockBody.Add(stmt);
            HandleStatement(stmt);
            _currentBlock = blockStmt;
            if (i != blockStmt.Body.Count - 1)
                InstrumentLine(stmt.EndToken);
        }
        blockStmt.Body = _newBlockBody;
        _newBlockBody = prevNewBlock;
    }
    
    protected override void VisitStatement(ProduceStmt pStmt) {
        if (pStmt is ReturnStmt rStmt && _currentBlock != null)
            _returnStmts.Add((rStmt, _currentBlock));
        base.VisitStatement(pStmt);
    }

    private void InstrumentLine(IOrigin token) {
        if (_currentTopLevelDecl == null) return;
        var availableIdentifiers = identifierAvailability.Where(
            id => 
                (token.pos > id.AvailabilityStartPos && token.pos < id.AvailabilityEndPos) || 
                (id.AvailabilityStartPos == null && id.AvailabilityEndPos == null)
        ).ToList();
        var newMethod = GenerateDummyMethod(token.pos, availableIdentifiers);
        if (newMethod == null) return;

        List<ActualBinding> arguments = [];
        List<Expression> callArgs = [];
        foreach (var identifier in availableIdentifiers) {
            var argumentName = new NameSegment(token, identifier.Name, null);
            AstUtils.ResolveNameSegment(argumentName, identifier);
            callArgs.Add(argumentName);
            arguments.Add(new ActualBinding(null, argumentName));
        }
        var methodName = new NameSegment(token, $"Dummy{token.pos}", null);
        var methodCall = new ApplySuffix(token, null, methodName, arguments, null);
        var newStmt = new AssignStatement(token, [], [new ExprRhs(token, methodCall)]);
        AstUtils.ResolveCallAssignStatement(newStmt, newMethod, callArgs, _currentTopLevelDecl);
        _newBlockBody.Add(newStmt);
    }

    private Method? GenerateDummyMethod(int dummyMethodID, List<Identifier> availableIdentifiers) {
        if (_currentTopLevelDecl == null) return null;
        var token = _currentTopLevelDecl.EndToken.MakeAutoGenerated();
        if (token == null) return null;
        
        var methodName = new Name(token, $"Dummy{dummyMethodID}");
        List<Formal> inputs = [];
        foreach (var identifier in availableIdentifiers) {
            inputs.Add(new Formal(
                token, identifier.Name, identifier.Type, true, false, null
            ));
        }

        var newMethod = new Method(
            token, methodName, null, false, false, [], inputs, [], [],
            new Specification<FrameExpression>([], null),
            new Specification<Expression>([], null), [],
            new Specification<FrameExpression>([], null),
            new BlockStmt(token, []), null
        ) { EnclosingClass = _currentTopLevelDecl };
        _newMethods.Add(newMethod);
        return newMethod;
    }
    
    private void AdjustTestExecution(Method method) {
        if (method.Body == null) return;
        foreach (var (stmt, i) in method.Body.Body.Select((stmt, i) => (stmt, i))) {
            if (stmt is not AssignStatement { Rhss: [ExprRhs { Expr: ApplySuffix { Lhs: NameSegment nSegExpr} }] })
                continue;
            if ((!InvariantInferrer.FailingInvariantInference && nSegExpr.Name == "Failing") ||
                (!InvariantInferrer.PassingInvariantInference && nSegExpr.Name == "Passing")) {
                method.Body.Body.RemoveAt(i);
                break;
            }
        }
    }

    /// -------------------------
    /// Daikon
    /// -------------------------
    private void AddHeader() {
        var method = SnapshotGenerator.FaultyMethod;
        if (method == null) return;
        
        var headerElement = AstUtils.CreateStringLiteral(method.Origin, "decl-version 2.0\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [headerElement]));
        headerElement = AstUtils.CreateStringLiteral(method.Origin, "input-language Dafny\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [headerElement]));
        var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
    }

    private void AddMethodDeclaration(Method method) {
        var faultyMethod = SnapshotGenerator.FaultyMethod;
        var mainMethod = SnapshotGenerator.MainMethod;
        if (faultyMethod == null || mainMethod == null) return;

        List<string> pointTypes = ["ENTER", "EXIT00"];
        if (method.Name == SnapshotGenerator.FaultyMethod?.Name) {
            for (var i = 0; i < _returnStmts.Count; i++)
                pointTypes.Add($"EXIT{i + 1}");
        }
        
        foreach (var type in pointTypes) {
            var programPointDecl = $"ppt {method.FullSanitizedName}():::{type}\\n";
            var declarationElement = AstUtils.CreateStringLiteral(mainMethod.Origin, programPointDecl);
            _newStmts.Add(new PrintStmt(mainMethod.Origin, [declarationElement]));
            var programPointType = type == "ENTER" ? "ppt-type enter\\n" : "ppt-type subexit\\n";
            declarationElement = AstUtils.CreateStringLiteral(mainMethod.Origin, programPointType);
            _newStmts.Add(new PrintStmt(mainMethod.Origin, [declarationElement]));

            if (method == faultyMethod) {
                AddFaultyMethodVariableDeclarations(method, type);
            } else {
                AddDummyMethodVariableDeclarations(method, type.StartsWith("EXIT"));
            }
            
            var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
            _newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
        }
    }

    private void AddFaultyMethodVariableDeclarations(Method method, string pointType) {
        var locationStartIndex = pointType.IndexOf("EXIT", StringComparison.Ordinal) + 7;
        var returnIdx = locationStartIndex < pointType.Length && 
            int.TryParse(pointType[locationStartIndex..], out var intVal) ? 
            intVal - 1 : _returnStmts.Count - 1;
        var position = pointType.EndsWith("ENTER") ? method.Body?.StartToken.pos : 
            pointType.EndsWith("EXIT") || pointType.EndsWith("EXIT00") ?
            method.Body?.EndToken.pos : _returnStmts[returnIdx].Item1.StartToken.pos;
        
        var availableIdentifiers = identifierAvailability.Where(
            id => 
                (position > id.AvailabilityStartPos && position <= id.AvailabilityEndPos) || 
                (id.AvailabilityStartPos == null && id.AvailabilityEndPos == null)
        ).ToList();
        foreach (var identifier in availableIdentifiers)
            AddVariableDeclaration(identifier.Name, identifier.Type, method.Origin);
    }

    private void AddDummyMethodVariableDeclarations(Method method, bool isExit) {
        var mainMethod = SnapshotGenerator.MainMethod;
        if (mainMethod == null) return;
        
        foreach (var input in method.Ins.Where(i => !i.IsGhost))
            AddVariableDeclaration(input.DisplayName, input.Type, mainMethod.Origin);
        if (!isExit) return;
        foreach (var output in method.Outs.Where(o => !o.IsGhost))
            AddVariableDeclaration(output.DisplayName, output.Type, mainMethod.Origin);
    }

    private void AddVariableDeclaration(string name, Type t, IOrigin token) {
        var decType = t.ToString().Replace(" ", "");
        var repType = DaikonFormatConverter.ToType(t);
        var comparability = DaikonFormatConverter.GetComparability(t);
        if (repType == "" || comparability == "") return;

        // arrays require two variable declarations: the array object itself and its contents
        if (DaikonFormatConverter.IsArrayType(t)) { // array object declaration
            AddVariableDeclaration(token, name, decType,
                "hashcode", "9", false);
        }
        // array contents and other variable types declaration
        AddVariableDeclaration(
            token, name, decType, repType, comparability, 
            DaikonFormatConverter.IsArrayType(t)
        );
    }

    private void AddVariableDeclaration(IOrigin token, string varName, string decType, string repType, string comparability, bool isArray) {
        var declarationElement = AstUtils.CreateStringLiteral(token, 
            $"variable {varName}{(isArray ? "[..]" : "")}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, 
            $"\tvar-kind {(isArray ? "array" : "variable")}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        if (isArray) {
            declarationElement = AstUtils.CreateStringLiteral(token, $"\tenclosing-var {varName}\\n");
            _newStmts.Add(new PrintStmt(token, [declarationElement]));
        }
        declarationElement = AstUtils.CreateStringLiteral(token, $"\tdec-type {decType}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, $"\trep-type {repType}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, $"\tcomparability {comparability}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
    }

    private void AddDummyMethodsDeclarations() {
        foreach (var dummyMethod in _newMethods) {
            AddMethodDeclaration(dummyMethod);
        }
    }

    private void AddMethodTracePoints(Method method) {
        // Add points at the method's entrance
        var newStmts = AddMethodTracePoints(method, "ENTER");
        if (method.Body == null) {
            method.Body = new BlockStmt(method.Origin, newStmts);
        } else {
            method.Body.Body = newStmts.Concat(method.Body.Body).ToList();
        }
        // Add points at the method's exit(s)
        if (method.Name == SnapshotGenerator.FaultyMethod?.Name) {
            foreach (var ((rStmt, block), i) in _returnStmts.Select((e, i) => (e, i))) {
                newStmts = AddMethodTracePoints(method, $"EXIT{i + 1}");
                var idx = block.Body.IndexOf(rStmt);
                block.Body.InsertRange(idx, newStmts);
            }
        }
        newStmts = AddMethodTracePoints(method, "EXIT00");
        method.Body.Body.AddRange(newStmts);
    }
    
    private List<Statement> AddMethodTracePoints(Method method, string ppt) {
        List<Statement> newStmts = [];
        var programPoint = $"{method.FullSanitizedName}():::{ppt}\\n";
        var declarationElement = AstUtils.CreateStringLiteral(method.Origin, programPoint);
        newStmts.Add(new PrintStmt(method.Origin, [declarationElement]));

        newStmts.AddRange(method == SnapshotGenerator.FaultyMethod
            ? AddFaultyMethodVariableTracePoints(method, ppt)
            : AddDummyMethodVariableTracePoints(method, ppt.StartsWith("EXIT")));

        var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
        newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
        return newStmts;
    }

    private List<Statement> AddFaultyMethodVariableTracePoints(Method method, string pointType) {
        List<Statement> newStmts = [];
        var locationStartIndex = pointType.IndexOf("EXIT", StringComparison.Ordinal) + 7;
        var returnIdx = locationStartIndex < pointType.Length && 
            int.TryParse(pointType[locationStartIndex..], out var intVal) ? 
            intVal - 1 : _returnStmts.Count - 1;
        var position = pointType.EndsWith("ENTER") ? method.Body?.StartToken.pos : 
            pointType.EndsWith("EXIT") || pointType.EndsWith("EXIT00") ?
                method.Body?.EndToken.pos : _returnStmts[returnIdx].Item1.StartToken.pos;
        
        var availableIdentifiers = identifierAvailability.Where(
            id => 
                (position > id.AvailabilityStartPos && position <= id.AvailabilityEndPos) || 
                (id.AvailabilityStartPos == null && id.AvailabilityEndPos == null)
        ).ToList();
        foreach (var identifier in availableIdentifiers) {
            newStmts.AddRange(AddVariableTracePoint(method, identifier));
        }
        return newStmts;
    }

    private List<Statement> AddDummyMethodVariableTracePoints(Method method, bool isExit) {
        List<Statement> newStmts = [];
        foreach (var input in method.Ins.Where(i => !i.IsGhost)) {
            var identifier = new Identifier(input, null, input.Type, null, null);
            newStmts.AddRange(AddVariableTracePoint(method, identifier));
        }
        if (!isExit) return newStmts;
        foreach (var output in method.Outs.Where(o => !o.IsGhost)) {
            var identifier = new Identifier(output, null, output.Type, null, null);
            newStmts.AddRange(AddVariableTracePoint(method, identifier));
        }
        return newStmts;
    }

    private List<Statement> AddVariableTracePoint(Method method, Identifier id) {
        var daikonValue = DaikonFormatConverter.ToDaikonValue(method.Origin, id);
        if (daikonValue == null)
            return [];
        
        List<Statement> newStmts = [];
        if (DaikonFormatConverter.IsArrayType(id.Type)) {
            // random hashcode since, for now, we are not interested in invariants related to this
            var hashcodeElem = AstUtils.CreateStringLiteral(method.Origin, "416153648\\n");
            var hashCodePrinter = new PrintStmt(method.Origin, [hashcodeElem]);
            newStmts.AddRange(AddVariableTracePoint(
                method.Origin, id.Name, hashCodePrinter, false
            ));
        }
        newStmts.AddRange(AddVariableTracePoint(method.Origin, id.Name, 
            daikonValue, DaikonFormatConverter.IsArrayType(id.Type)));
        return newStmts;
    }

    private List<Statement> AddVariableTracePoint(IOrigin token, string varName, Statement varValuePrinter, bool isArray) {
        List<Statement> newStmts = [];
        // Print the name of the variable
        var varIdentification = AstUtils.CreateStringLiteral(token, 
            $"{varName}{(isArray ? "[..]" : "")}\\n"
        );
        newStmts.Add(new PrintStmt(token, [varIdentification]));
        // Print the value of the variable
        newStmts.Add(varValuePrinter);
        // Print the modified bit
        var modBit = Expression.CreateIntLiteral(token, 0);
        var delimElement = AstUtils.CreateStringLiteral(token, "\\n");
        newStmts.Add(new PrintStmt(token, [modBit, delimElement]));
        return newStmts;
    }
    
    private void AddDummyMethodsTracePoints() {
        foreach (var dummyMethod in _newMethods) {
            AddMethodTracePoints(dummyMethod);
        }
    }
}