using Microsoft.Dafny;
using Type = Microsoft.Dafny.Type;

namespace SnapshotGenerator.InvariantInference;

public class DaikonInstrumenter(List<(IVariable?, MemberDecl?, string, Type, int?, int?)> identifierAvailability) : Visitor(true)
{
    private TopLevelDeclWithMembers? _currentTopLevelDecl;
    private BlockStmt? _currentBlock;
    private readonly List<Method> _newMethods = [];
    private List<Statement> _newBlockBody = [];
    private readonly List<Statement> _newStmts = [];
    private readonly List<(ReturnStmt, BlockStmt)> _returnStmts = [];
    
    public void Instrument(ModuleDefinition module) {
        Visit(module);
        if (SnapshotGenerator.MainMethod == null || 
            SnapshotGenerator.FaultyMethod == null)
            return;
        var mainMethod = SnapshotGenerator.MainMethod;
        var faultyMethod = SnapshotGenerator.FaultyMethod;
        AdjustTestExecution(mainMethod);
        
        AddHeader();
        AddMethodDeclaration(faultyMethod);
        AddDummyMethodsDeclarations();
        if (mainMethod.Body == null) {
            mainMethod.Body = new BlockStmt(mainMethod.Origin, _newStmts);
        } else {
            mainMethod.Body.Body = _newStmts.Concat(mainMethod.Body.Body).ToList();  
        }
        AddMethodTracePoints(faultyMethod);
        AddDummyMethodsTracePoints();
    }
    
    protected override void HandleMemberDecls(TopLevelDeclWithMembers decl) {
        _currentTopLevelDecl = decl;
        base.HandleMemberDecls(decl);
        decl.Members.AddRange(_newMethods);
    }
    
    protected override void HandleMethod(Method method) {
        // find Main, i.e., entrypoint, where the faulty method is being exercised
        if (method.Name == "Main")
            SnapshotGenerator.MainMethod = method;
        // find the faulty method, i.e., where the violation occurs  
        if (!(method.StartToken.line <= SnapshotGenerator.ViolationLine &&
              method.EndToken.line >= SnapshotGenerator.ViolationLine))
            return;
        SnapshotGenerator.FaultyMethod = method;
        
        // instrument the method with calls to dummy methods for invariant inference
        if (method.Body != null)
            HandleBlock(method.Body);
    }
    
    /// -------------------------
    /// Instrumentation
    /// -------------------------
    protected override void HandleBlock(BlockStmt blockStmt) {
        _currentBlock = blockStmt;
        var prevNewBlock = _newBlockBody;
        _newBlockBody = [];
        foreach (var (stmt, i) in blockStmt.Body.Select((stmt, i) => (stmt, i))) {
            _newBlockBody.Add(stmt);
            HandleStatement(stmt);
            _currentBlock = blockStmt;
            if (i != blockStmt.Body.Count - 1)
                InstrumentLine(stmt.EndToken);
        }
        blockStmt.Body = _newBlockBody;
        _newBlockBody = prevNewBlock;
    }
    
    protected override void VisitStatement(ProduceStmt pStmt) {
        if (pStmt is ReturnStmt rStmt && _currentBlock != null)
            _returnStmts.Add((rStmt, _currentBlock));
        base.VisitStatement(pStmt);
    }

    private void InstrumentLine(IOrigin token) {
        if (_currentTopLevelDecl == null) return;
        var availableIdentifiers = identifierAvailability.Where(
            expr => 
                (token.pos > expr.Item5 && token.pos < expr.Item6) || 
                (expr.Item5 == null && expr.Item6 == null)
        ).ToList();
        var newMethod = GenerateDummyMethod(token.pos, availableIdentifiers);
        if (newMethod == null) return;

        List<ActualBinding> arguments = [];
        List<Expression> callArgs = [];
        foreach (var identifier in availableIdentifiers) {
            var argumentName = new NameSegment(token, identifier.Item3, null);
            AstUtils.ResolveNameSegment(argumentName, identifier.Item4, identifier.Item1, identifier.Item2, _currentTopLevelDecl);
            callArgs.Add(argumentName);
            arguments.Add(new ActualBinding(null, argumentName));
        }
        var methodName = new NameSegment(token, $"Dummy{token.pos}", null);
        var methodCall = new ApplySuffix(token, null, methodName, arguments, null);
        var newStmt = new AssignStatement(token, [], [new ExprRhs(token, methodCall)]);
        AstUtils.ResolveCallAssignStatement(newStmt, newMethod, callArgs, _currentTopLevelDecl);
        _newBlockBody.Add(newStmt);
    }

    private Method? GenerateDummyMethod(int dummyMethodID, List<(IVariable?, MemberDecl?, string, Type, int?, int?)> availableIdentifiers) {
        if (_currentTopLevelDecl == null) return null;
        var token = _currentTopLevelDecl.EndToken.MakeAutoGenerated();
        if (token == null) return null;
        
        var methodName = new Name(token, $"Dummy{dummyMethodID}");
        List<Formal> inputs = [];
        foreach (var identifier in availableIdentifiers) {
            inputs.Add(new Formal(
                token, identifier.Item3, identifier.Item4, true, false, null
            ));
        }

        var newMethod = new Method(
            token, methodName, null, false, false, [], inputs, [], [],
            new Specification<FrameExpression>([], null),
            new Specification<Expression>([], null), [],
            new Specification<FrameExpression>([], null),
            new BlockStmt(token, []), null
        ) { EnclosingClass = _currentTopLevelDecl };
        _newMethods.Add(newMethod);
        return newMethod;
    }
    
    private void AdjustTestExecution(Method method) {
        if (method.Body == null) return;
        foreach (var (stmt, i) in method.Body.Body.Select((stmt, i) => (stmt, i))) {
            if (stmt is not AssignStatement { Rhss: [ExprRhs { Expr: ApplySuffix { Lhs: NameSegment nSegExpr} }] })
                continue;
            if ((!InvariantInferrer.FailingInvariantInference && nSegExpr.Name == "Failing") ||
                (!InvariantInferrer.PassingInvariantInference && nSegExpr.Name == "Passing")) {
                method.Body.Body.RemoveAt(i);
                break;
            }
        }
    }

    /// -------------------------
    /// Daikon
    /// -------------------------
    private void AddHeader() {
        var method = SnapshotGenerator.FaultyMethod;
        if (method == null) return;
        
        var headerElement = AstUtils.CreateStringLiteral(method.Origin, "decl-version 2.0\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [headerElement]));
        headerElement = AstUtils.CreateStringLiteral(method.Origin, "input-language Dafny\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [headerElement]));
        var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
    }

    private void AddMethodDeclaration(Method method) {
        var mainMethod = SnapshotGenerator.MainMethod;
        if (mainMethod == null) return;

        List<string> pointTypes = ["ENTER", "EXIT00"];
        if (method.Name == SnapshotGenerator.FaultyMethod?.Name) {
            for (var i = 0; i < _returnStmts.Count; i++)
                pointTypes.Add($"EXIT{i + 1}");
        }
        
        foreach (var type in pointTypes) {
            var programPointDecl = $"ppt {method.FullSanitizedName}():::{type}\\n";
            var declarationElement = AstUtils.CreateStringLiteral(mainMethod.Origin, programPointDecl);
            _newStmts.Add(new PrintStmt(mainMethod.Origin, [declarationElement]));
            var programPointType = type == "ENTER" ? "ppt-type enter\\n" : "ppt-type subexit\\n";
            declarationElement = AstUtils.CreateStringLiteral(mainMethod.Origin, programPointType);
            _newStmts.Add(new PrintStmt(mainMethod.Origin, [declarationElement]));


            foreach (var input in method.Ins.Where(i => !i.IsGhost))
                AddVariableDeclaration(input, mainMethod.Origin);
            if (type.StartsWith("EXIT")) {
                foreach (var output in method.Outs.Where(o => !o.IsGhost))
                    AddVariableDeclaration(output, mainMethod.Origin);
            }
            
            var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
            _newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
        }
    }

    private void AddVariableDeclaration(Formal f, IOrigin token) {
        var decType = f.Type.ToString().Replace(" ", "");
        var repType = DaikonFormatConverter.ToType(f.Type);
        var comparability = DaikonFormatConverter.GetComparability(f.Type);
        if (repType == "" || comparability == "") return;

        // arrays require two variable declarations: the array object itself and its contents
        if (DaikonFormatConverter.IsArrayType(f.Type)) { // array object declaration
            AddVariableDeclaration(token, f.DisplayName, decType,
                "hashcode", "9", false);
        }
        // array contents and other variable types declaration
        AddVariableDeclaration(token, f.DisplayName, 
            decType, repType, comparability, 
            DaikonFormatConverter.IsArrayType(f.Type)
        );
    }

    private void AddVariableDeclaration(IOrigin token, string varName, string decType, string repType, string comparability, bool isArray) {
        var declarationElement = AstUtils.CreateStringLiteral(token, 
            $"variable {varName}{(isArray ? "[..]" : "")}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, 
            $"\tvar-kind {(isArray ? "array" : "variable")}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        if (isArray) {
            declarationElement = AstUtils.CreateStringLiteral(token, $"\tenclosing-var {varName}\\n");
            _newStmts.Add(new PrintStmt(token, [declarationElement]));
        }
        declarationElement = AstUtils.CreateStringLiteral(token, $"\tdec-type {decType}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, $"\trep-type {repType}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, $"\tcomparability {comparability}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
    }

    private void AddDummyMethodsDeclarations() {
        foreach (var dummyMethod in _newMethods) {
            AddMethodDeclaration(dummyMethod);
        }
    }

    private void AddMethodTracePoints(Method method) {
        // Add points at the method's entrance
        var newStmts = AddMethodTracePoints(method, "ENTER");
        if (method.Body == null) {
            method.Body = new BlockStmt(method.Origin, newStmts);
        } else {
            method.Body.Body = newStmts.Concat(method.Body.Body).ToList();
        }
        // Add points at the method's exit(s)
        if (method.Name == SnapshotGenerator.FaultyMethod?.Name) {
            foreach (var ((rStmt, block), i) in _returnStmts.Select((e, i) => (e, i))) {
                newStmts = AddMethodTracePoints(method, $"EXIT{i + 1}");
                var idx = block.Body.IndexOf(rStmt);
                block.Body.InsertRange(idx, newStmts);
            }
        }
        newStmts = AddMethodTracePoints(method, "EXIT00");
        method.Body.Body.AddRange(newStmts);
    }
    
    private List<Statement> AddMethodTracePoints(Method method, string ppt) {
        List<Statement> newStmts = [];
        var programPoint = $"{method.FullSanitizedName}():::{ppt}\\n";
        var declarationElement = AstUtils.CreateStringLiteral(method.Origin, programPoint);
        newStmts.Add(new PrintStmt(method.Origin, [declarationElement]));
        
        foreach (var input in method.Ins.Where(i => !i.IsGhost))
            newStmts.AddRange(AddVariableTracePoint(method, input));
        if (ppt.StartsWith("EXIT")) {
            foreach (var output in method.Outs.Where(o => !o.IsGhost))
                newStmts.AddRange(AddVariableTracePoint(method, output));
        }
        
        var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
        newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
        return newStmts;
    }

    private List<Statement> AddVariableTracePoint(Method method, Formal f) {
        var daikonValue = DaikonFormatConverter.ToDaikonValue(method.Origin, f);
        if (daikonValue == null)
            return [];
        
        List<Statement> newStmts = [];
        if (DaikonFormatConverter.IsArrayType(f.Type)) {
            // random hashcode since, for now, we are not interested in invariants related to this
            var hashcodeElem = AstUtils.CreateStringLiteral(method.Origin, "416153648\\n");
            var hashCodePrinter = new PrintStmt(method.Origin, [hashcodeElem]);
            newStmts.AddRange(AddVariableTracePoint(
                method.Origin, f.DisplayName, hashCodePrinter, false
            ));
        }
        newStmts.AddRange(AddVariableTracePoint(method.Origin, f.DisplayName, 
            daikonValue, DaikonFormatConverter.IsArrayType(f.Type)));
        return newStmts;
    }

    private List<Statement> AddVariableTracePoint(IOrigin token, string varName, Statement varValuePrinter, bool isArray) {
        List<Statement> newStmts = [];
        // Print the name of the variable
        var varIdentification = AstUtils.CreateStringLiteral(token, 
            $"{varName}{(isArray ? "[..]" : "")}\\n"
        );
        newStmts.Add(new PrintStmt(token, [varIdentification]));
        // Print the value of the variable
        newStmts.Add(varValuePrinter);
        // Print the modified bit
        var modBit = Expression.CreateIntLiteral(token, 0);
        var delimElement = AstUtils.CreateStringLiteral(token, "\\n");
        newStmts.Add(new PrintStmt(token, [modBit, delimElement]));
        return newStmts;
    }
    
    private void AddDummyMethodsTracePoints() {
        foreach (var dummyMethod in _newMethods) {
            AddMethodTracePoints(dummyMethod);
        }
    }
}