using Microsoft.Dafny;
using Type = Microsoft.Dafny.Type;

namespace SnapshotGenerator.InvariantInference;

public class DaikonInstrumenter(List<(IVariable?, MemberDecl?, string, Type, int?, int?)> identifierAvailability) : Visitor(true)
{
    private TopLevelDeclWithMembers? _currentTopLevelDecl;
    private int _dummyMethodId = 1; 
    private readonly List<Method> _newMethods = [];
    private List<Statement> _newBlockBody = [];
    private readonly List<Statement> _newStmts = [];
    
    public void Instrument(ModuleDefinition module) {
        Visit(module);
        if (InvariantInferrer.MainMethod == null || 
            InvariantInferrer.FaultyMethod == null)
            return;
        var mainMethod = InvariantInferrer.MainMethod;
        var faultyMethod = InvariantInferrer.FaultyMethod;
        AdjustTestExecution(mainMethod);
        
        AddHeader();
        AddMethodDeclaration(faultyMethod);
        AddDummyMethodsDeclarations();
        if (mainMethod.Body == null) {
            mainMethod.Body = new BlockStmt(mainMethod.Origin, _newStmts);
        } else {
            mainMethod.Body.Body = _newStmts.Concat(mainMethod.Body.Body).ToList();  
        }
        AddMethodTracePoints(faultyMethod);
        AddDummyMethodsTracePoints();
    }
    
    protected override void HandleMemberDecls(TopLevelDeclWithMembers decl) {
        _currentTopLevelDecl = decl;
        base.HandleMemberDecls(decl);
        decl.Members.AddRange(_newMethods);
    }
    
    protected override void HandleMethod(Method method) {
        // find Main, i.e., entrypoint, where the faulty method is being exercised
        if (method.Name == "Main")
            InvariantInferrer.MainMethod = method;
        // find the faulty method, i.e., where the violation occurs  
        if (!(method.StartToken.line <= SnapshotGenerator.ViolationLine &&
              method.EndToken.line >= SnapshotGenerator.ViolationLine))
            return;
        InvariantInferrer.FaultyMethod = method;
        
        // instrument the method with calls to dummy methods for invariant inferrence
        if (method.Body != null)
            HandleBlock(method.Body);
    }
    
    /// -------------------------
    /// Instrumentation
    /// -------------------------
    protected override void HandleBlock(BlockStmt blockStmt) {
        var prevNewBlock = _newBlockBody;
        _newBlockBody = [];
        foreach (var (stmt, i) in blockStmt.Body.Select((stmt, i) => (stmt, i))) {
            _newBlockBody.Add(stmt);
            HandleStatement(stmt);
            if (i != blockStmt.Body.Count - 1)
                InstrumentLine(stmt.EndToken);
        }
        blockStmt.Body = _newBlockBody;
        _newBlockBody = prevNewBlock;
    }

    private void InstrumentLine(IOrigin token) {
        if (_currentTopLevelDecl == null) return;
        var availableIdentifiers = identifierAvailability.Where(
            expr => 
                (token.pos > expr.Item5 && token.pos < expr.Item6) || 
                (expr.Item5 == null && expr.Item6 == null)
        ).ToList();
        var newMethod = GenerateDummyMethod(availableIdentifiers);
        if (newMethod == null) return;

        List<ActualBinding> arguments = [];
        List<Expression> callArgs = [];
        foreach (var identifier in availableIdentifiers) {
            var argumentName = new NameSegment(token, identifier.Item3, null);
            AstUtils.ResolveNameSegment(argumentName, identifier.Item4, identifier.Item1, identifier.Item2, _currentTopLevelDecl);
            callArgs.Add(argumentName);
            arguments.Add(new ActualBinding(null, argumentName));
        }
        var methodName = new NameSegment(token, $"Dummy{_dummyMethodId}", null);
        var methodCall = new ApplySuffix(token, null, methodName, arguments, null);
        var newStmt = new AssignStatement(token, [], [new ExprRhs(token, methodCall)]);
        AstUtils.ResolveCallAssignStatement(newStmt, newMethod, callArgs, _currentTopLevelDecl);
        _newBlockBody.Add(newStmt);
        _dummyMethodId++;
    }

    private Method? GenerateDummyMethod(List<(IVariable?, MemberDecl?, string, Type, int?, int?)> availableIdentifiers) {
        if (_currentTopLevelDecl == null) return null;
        var token = _currentTopLevelDecl.EndToken.MakeAutoGenerated();
        if (token == null) return null;
        
        var methodName = new Name(token, $"Dummy{_dummyMethodId}");
        List<Formal> inputs = [];
        foreach (var identifier in availableIdentifiers) {
            inputs.Add(new Formal(
                token, identifier.Item3, identifier.Item4, true, false, null
            ));
        }

        var newMethod = new Method(
            token, methodName, null, false, false, [], inputs, [], [],
            new Specification<FrameExpression>([], null),
            new Specification<Expression>([], null), [],
            new Specification<FrameExpression>([], null),
            new BlockStmt(token, []), null
        ) { EnclosingClass = _currentTopLevelDecl };
        _newMethods.Add(newMethod);
        return newMethod;
    }
    
    private void AdjustTestExecution(Method method) {
        if (method.Body == null) return;
        foreach (var (stmt, i) in method.Body.Body.Select((stmt, i) => (stmt, i))) {
            if (stmt is not AssignStatement { Rhss: [ExprRhs { Expr: ApplySuffix { Lhs: NameSegment nSegExpr} }] })
                continue;
            if ((InvariantInferrer.PassingInvariantInference && nSegExpr.Name == "Failing") ||
                (!InvariantInferrer.PassingInvariantInference && nSegExpr.Name == "Passing")) {
                method.Body.Body.RemoveAt(i);
                break;
            }
        }
    }

    /// -------------------------
    /// Daikon
    /// -------------------------
    private void AddHeader() {
        var method = InvariantInferrer.FaultyMethod;
        if (method == null) return;
        
        var headerElement = AstUtils.CreateStringLiteral(method.Origin, "decl-version 2.0\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [headerElement]));
        headerElement = AstUtils.CreateStringLiteral(method.Origin, "input-language Dafny\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [headerElement]));
        var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
        _newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
    }

    private void AddMethodDeclaration(Method method) {
        var mainMethod = InvariantInferrer.MainMethod;
        if (mainMethod == null) return;
        
        foreach (var type in new List<string> { "ENTER", "EXIT00" }) {
            var programPointDecl = $"ppt {method.FullSanitizedName}():::{type}\\n";
            var declarationElement = AstUtils.CreateStringLiteral(mainMethod.Origin, programPointDecl);
            _newStmts.Add(new PrintStmt(mainMethod.Origin, [declarationElement]));
            var programPointType = type == "ENTER" ? "ppt-type enter\\n" : "ppt-type subexit\\n";
            declarationElement = AstUtils.CreateStringLiteral(mainMethod.Origin, programPointType);
            _newStmts.Add(new PrintStmt(mainMethod.Origin, [declarationElement]));


            foreach (var input in method.Ins)
                AddVariableDeclaration(input, mainMethod.Origin);
            if (type == "EXIT00") {
                foreach (var output in method.Outs)
                    AddVariableDeclaration(output, mainMethod.Origin);
            }
            
            var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
            _newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
        }
    }

    private void AddVariableDeclaration(Formal f, IOrigin token) {
        var repType = DaikonFormatConverter.ToType(f.Type);
        var comparability = DaikonFormatConverter.GetComparability(f.Type);
        if (repType == "" || comparability == "") return;
        
        var declarationElement = AstUtils.CreateStringLiteral(token, 
            $"variable {f.CompileName}{(DaikonFormatConverter.IsArrayType(f.Type) ? "[..]" : "")}\\n"
        );
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, "\tvar-kind variable\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        declarationElement = AstUtils.CreateStringLiteral(token, $"\tdec-type {f.Type.ToString().Replace(" ", "")}\\n");
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        repType = "\trep-type " + $"{repType}\\n";
        declarationElement = AstUtils.CreateStringLiteral(token, repType);
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
        comparability = "\tcomparability " + $"{comparability}\\n";
        declarationElement = AstUtils.CreateStringLiteral(token, comparability);
        _newStmts.Add(new PrintStmt(token, [declarationElement]));
    }

    private void AddDummyMethodsDeclarations() {
        foreach (var dummyMethod in _newMethods) {
            AddMethodDeclaration(dummyMethod);
        }
    }

    private void AddMethodTracePoints(Method method) {
        // Add points at the method's entrance
        var newStmts = AddMethodTracePoints(method, true);
        if (method.Body == null) {
            method.Body = new BlockStmt(method.Origin, newStmts);
        } else {
            method.Body.Body = newStmts.Concat(method.Body.Body).ToList();
        }
        // Add points at the method's exit
        newStmts = AddMethodTracePoints(method, false);
        method.Body.Body.AddRange(newStmts);
    }
    
    private List<Statement> AddMethodTracePoints(Method method, bool isEntrance) {
        List<Statement> newStmts = [];
        var type = isEntrance ? "ENTER" : "EXIT00";
        var programPoint = $"{method.FullSanitizedName}():::{type}\\n";
        var declarationElement = AstUtils.CreateStringLiteral(method.Origin, programPoint);
        newStmts.Add(new PrintStmt(method.Origin, [declarationElement]));
        
        foreach (var input in method.Ins)
            newStmts.AddRange(AddVariableTracePoint(method, input));
        if (!isEntrance) {
            foreach (var output in method.Outs)
                newStmts.AddRange(AddVariableTracePoint(method, output));
        }
        
        var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
        newStmts.Add(new PrintStmt(method.Origin, [delimElement]));
        return newStmts;
    }

    private List<Statement> AddVariableTracePoint(Method method, Formal f) {
        var daikonValue = DaikonFormatConverter.ToDaikonValue(method.Origin, f);
        if (daikonValue == null)
            return [];
        
        List<Statement> newStmts = [];
        // Print the name of the variable
        var varIdentification = AstUtils.CreateStringLiteral(method.Origin, 
            $"{f.CompileName}{(DaikonFormatConverter.IsArrayType(f.Type) ? "[..]" : "")}\\n"
        );
        newStmts.Add(new PrintStmt(method.Origin, [varIdentification]));
        // Print the value of the variable
        newStmts.Add(daikonValue);
        // Print the modified bit
        var modBit = Expression.CreateIntLiteral(method.Origin, 0);
        var delimElement = AstUtils.CreateStringLiteral(method.Origin, "\\n");
        newStmts.Add(new PrintStmt(method.Origin, [modBit, delimElement]));
        return newStmts;
    }
    
    private void AddDummyMethodsTracePoints() {
        foreach (var dummyMethod in _newMethods) {
            AddMethodTracePoints(dummyMethod);
        }
    }
}